In [1]:
from matrix import build_matrix
from matrix import integer_inequality
import numpy as np
from scipy.sparse import coo_matrix
from matplotlib import pyplot as plt
import scipy.sparse
from scipy.sparse.linalg import eigsh
from scipy.sparse.linalg import eigs
from Reproduce import main

In [ ]:
exponent = np.arange(16)
q_values = 10 ** (-exponent / 3)
k_values = [20, 50, 100, 200, 400, 800]
main(q_values, k_values, 'reproduce_1000_undirected_with_averaging', 100)

[[-10, 0, 0], [-9, 0, 0], [-8, 0, 0], [-7, 0, 0], [-6, 0, 0], [-5, 0, 0], [-4, 0, 0], [-3, 0, 0], [-2, 0, 0], [-1, 0, 0], [1, 0, 0], [2, 0, 0], [3, 0, 0], [4, 0, 0], [5, 0, 0], [6, 0, 0], [7, 0, 0], [8, 0, 0], [9, 0, 0], [10, 0, 0]]
edges 20000
one k done. 20
[[-25, 0, 0], [-24, 0, 0], [-23, 0, 0], [-22, 0, 0], [-21, 0, 0], [-20, 0, 0], [-19, 0, 0], [-18, 0, 0], [-17, 0, 0], [-16, 0, 0], [-15, 0, 0], [-14, 0, 0], [-13, 0, 0], [-12, 0, 0], [-11, 0, 0], [-10, 0, 0], [-9, 0, 0], [-8, 0, 0], [-7, 0, 0], [-6, 0, 0], [-5, 0, 0], [-4, 0, 0], [-3, 0, 0], [-2, 0, 0], [-1, 0, 0], [1, 0, 0], [2, 0, 0], [3, 0, 0], [4, 0, 0], [5, 0, 0], [6, 0, 0], [7, 0, 0], [8, 0, 0], [9, 0, 0], [10, 0, 0], [11, 0, 0], [12, 0, 0], [13, 0, 0], [14, 0, 0], [15, 0, 0], [16, 0, 0], [17, 0, 0], [18, 0, 0], [19, 0, 0], [20, 0, 0], [21, 0, 0], [22, 0, 0], [23, 0, 0], [24, 0, 0], [25, 0, 0]]
edges 50000
one k done. 50
[[-50, 0, 0], [-49, 0, 0], [-48, 0, 0], [-47, 0, 0], [-46, 0, 0], [-45, 0, 0], [-44, 0, 0], [-43, 0, 0], 

In [2]:
z = build_matrix('1d_ring_1000', np.array([10, 1, 1]), 2)
z.all_indices()
z.one_int_index_tuples_and_adjacency()
z.Laplacian_0()

[[-2, 0, 0], [-1, 0, 0], [1, 0, 0], [2, 0, 0]]
edges 40


In [5]:
print(z.L_rnd.toarray())

[[-4.  0.  1.  0.  0.  0.  0.  1.  1.  1.]
 [ 0. -4.  1.  0.  1.  0.  0.  1.  0.  1.]
 [ 1.  1. -5.  1.  1.  0.  0.  0.  0.  1.]
 [ 0.  0.  1. -3.  1.  0.  0.  0.  1.  0.]
 [ 0.  1.  1.  1. -4.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -3.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1. -3.  0.  1.  1.]
 [ 1.  1.  0.  0.  0.  1.  0. -4.  1.  0.]
 [ 1.  0.  0.  1.  0.  0.  1.  1. -5.  1.]
 [ 1.  1.  1.  0.  0.  0.  1.  0.  1. -5.]]


In [4]:
print(z.L_0.toarray())

[[-4.  1.  1.  0.  0.  0.  0.  0.  1.  1.]
 [ 1. -4.  1.  1.  0.  0.  0.  0.  0.  1.]
 [ 1.  1. -4.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  1. -4.  1.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  1. -4.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  1. -4.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1. -4.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.  1. -4.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.  1. -4.  1.]
 [ 1.  1.  0.  0.  0.  0.  0.  1.  1. -4.]]


In [3]:
lam = np.zeros(100)
for i in range(100):
    z.random_rewiring(1)
    lam[i] = z.second_largest_eigenvalue()
print(np.mean(lam)/10)

1.2323772778806172


In [3]:
z.random_rewiring(0.4)

In [46]:
#z.random_rewiring(1)
print(z.second_largest_eigenvalue(8, 1.2)/200)

0.7535274934026185


In [7]:
q_values = [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]
k_values = [20, 50, 100, 200, 400, 800]
dictq = {str(q):[] for q in q_values}
dictionary = {str(k):dictq for k in k_values}

In [6]:
dictionary[str(20)][str(1e-5)].append(1)

In [7]:
print(dictionary)

{'20': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '50': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '100': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '200': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '400': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '800': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}}


In [10]:
x = np.array([1,2,3,4,5,6])
y= np.array([2,4,5,5,6,4])
print(np.array([x[np.array([0,1,3])], y[np.array([1,2,0])]]).T)

[[1 4]
 [2 5]
 [4 2]]
