In [1]:
from matrix import build_matrix
from matrix import integer_inequality
import numpy as np
from scipy.sparse import coo_matrix
from matplotlib import pyplot as plt
import scipy.sparse
from scipy.sparse.linalg import eigsh
from scipy.sparse.linalg import eigs
from Reproduce import main

In [ ]:
exponent = np.arange(16)
q_values = 10 ** (-exponent / 3)
k_values = [20, 50, 100, 200, 400, 800]
main(q_values, k_values, 'reproduce_1000_undirected_with_averaging', 100)

[[-10, 0, 0], [-9, 0, 0], [-8, 0, 0], [-7, 0, 0], [-6, 0, 0], [-5, 0, 0], [-4, 0, 0], [-3, 0, 0], [-2, 0, 0], [-1, 0, 0], [1, 0, 0], [2, 0, 0], [3, 0, 0], [4, 0, 0], [5, 0, 0], [6, 0, 0], [7, 0, 0], [8, 0, 0], [9, 0, 0], [10, 0, 0]]
edges 20000
one k done. 20
[[-25, 0, 0], [-24, 0, 0], [-23, 0, 0], [-22, 0, 0], [-21, 0, 0], [-20, 0, 0], [-19, 0, 0], [-18, 0, 0], [-17, 0, 0], [-16, 0, 0], [-15, 0, 0], [-14, 0, 0], [-13, 0, 0], [-12, 0, 0], [-11, 0, 0], [-10, 0, 0], [-9, 0, 0], [-8, 0, 0], [-7, 0, 0], [-6, 0, 0], [-5, 0, 0], [-4, 0, 0], [-3, 0, 0], [-2, 0, 0], [-1, 0, 0], [1, 0, 0], [2, 0, 0], [3, 0, 0], [4, 0, 0], [5, 0, 0], [6, 0, 0], [7, 0, 0], [8, 0, 0], [9, 0, 0], [10, 0, 0], [11, 0, 0], [12, 0, 0], [13, 0, 0], [14, 0, 0], [15, 0, 0], [16, 0, 0], [17, 0, 0], [18, 0, 0], [19, 0, 0], [20, 0, 0], [21, 0, 0], [22, 0, 0], [23, 0, 0], [24, 0, 0], [25, 0, 0]]
edges 50000
one k done. 50
[[-50, 0, 0], [-49, 0, 0], [-48, 0, 0], [-47, 0, 0], [-46, 0, 0], [-45, 0, 0], [-44, 0, 0], [-43, 0, 0], 

In [2]:
z = build_matrix('1d_ring_1000', np.array([1000, 1, 1]), 10)
z.all_indices()
z.one_int_index_tuples_and_adjacency()
z.Laplacian_0()

[[-10, 0, 0], [-9, 0, 0], [-8, 0, 0], [-7, 0, 0], [-6, 0, 0], [-5, 0, 0], [-4, 0, 0], [-3, 0, 0], [-2, 0, 0], [-1, 0, 0], [1, 0, 0], [2, 0, 0], [3, 0, 0], [4, 0, 0], [5, 0, 0], [6, 0, 0], [7, 0, 0], [8, 0, 0], [9, 0, 0], [10, 0, 0]]
edges 20000


In [9]:
print(z.L_rnd.toarray())

[[-23.   0.   0. ...   0.   0.   0.]
 [  0. -25.   1. ...   0.   0.   0.]
 [  0.   1. -18. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ... -22.   0.   1.]
 [  0.   0.   0. ...   0. -18.   0.]
 [  0.   0.   0. ...   1.   0. -16.]]


In [15]:
%matplotlib qt
plt.imshow(z.L_rnd.toarray(), vmin=-1, vmax=1)

In [4]:
lam=np.zeros(10)
for i in range(10):
    z.random_rewiring(1)
    lam[i]=z.second_largest_eigenvalue(8, 1.2)/20
print(np.mean(lam))

-0.491432258197694


In [3]:
lam = np.zeros(100)
for i in range(100):
    z.random_rewiring(1)
    lam[i] = z.second_largest_eigenvalue()
print(np.mean(lam)/10)

1.2323772778806172


In [16]:
z.random_rewiring(1)
print(z.L_rnd.toarray())

[[-23.   0.   0. ...   0.   0.   0.]
 [  0. -21.   0. ...   0.   0.   1.]
 [  0.   0. -26. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ... -30.   0.   0.]
 [  0.   0.   0. ...   0. -19.   0.]
 [  0.   1.   0. ...   0.   0. -16.]]


In [3]:
z.random_rewiring(1)
print(z.second_largest_eigenvalue(8, 1.2)/20)

-0.49881384944856794


In [7]:
q_values = [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]
k_values = [20, 50, 100, 200, 400, 800]
dictq = {str(q):[] for q in q_values}
dictionary = {str(k):dictq for k in k_values}

In [6]:
dictionary[str(20)][str(1e-5)].append(1)

In [7]:
print(dictionary)

{'20': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '50': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '100': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '200': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '400': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '800': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}}


In [4]:
import networkx as nx

ModuleNotFoundError: No module named 'networkx'

In [6]:
np.random.binomial(200, 1)

200

In [12]:
from scipy.sparse import csr_matrix, triu, tril, find
A = csr_matrix([[1, 2, 0, 0, 3], [4, 5, 0, 6, 7], [0, 0, 8, 9, 0],[1,1,1,5,4],[0,0,0,3,4]],dtype='int32')

In [11]:
print(tril(A,k=4-5).toarray())

[[0 0 0 0 0]
 [4 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 0 0]
 [0 0 0 3 0]]


In [10]:
print(A.getrow(2).toarray())

[[0 0 8 9 0]]


In [18]:
print(find(triu(A,k=1)))

(array([0, 1, 2, 0, 1, 3], dtype=int32), array([1, 3, 3, 4, 4, 4], dtype=int32), array([2, 6, 9, 3, 7, 4], dtype=int32))


In [17]:
A_new =A
A_new+=A_new
print(A.toarray(), A_new.toarray())

[[1 2 0 0 3]
 [4 5 0 6 7]
 [0 0 8 9 0]
 [1 1 1 5 4]
 [0 0 0 3 4]] [[ 2  4  0  0  6]
 [ 8 10  0 12 14]
 [ 0  0 16 18  0]
 [ 2  2  2 10  8]
 [ 0  0  0  6  8]]


In [39]:
x = np.array([1,1,1,2,2,3,1,3,4,7,8])

In [40]:
np.bincount(x)

array([0, 4, 2, 2, 1, 0, 0, 1, 1], dtype=int64)

In [43]:
y = find(csc(x))
print(y)

NameError: name 'csc' is not defined

In [7]:
print(type(np.append([1,2,3],[2,2,3])))

<class 'numpy.ndarray'>


In [20]:
N = 1000
for k in [20, 50, 100]:
    print(k,N,2*np.sqrt(1/k -1/N)-1)

20 1000 -0.5572811275764269
50 1000 -0.7243190249581956
100 1000 -0.8102633403898972
