In [2]:
from matrix import build_matrix
from matrix import integer_inequality
import numpy as np
from scipy.sparse import coo_matrix
#from matplotlib import pyplot as plt
import scipy.sparse
from scipy.sparse.linalg import eigsh
from scipy.sparse.linalg import eigs
from Reproduce import main
import time

In [2]:
import numpy as np
import sys
print(sys.executable)

/home/h3/s8583916/user-kernel/mykernel/bin/python


In [5]:
start = time.time()
exponent = np.arange(16)
q_values = 10 ** (-exponent / 3)
q_values=[0.01]#[0.01, 0.1]
#k_values = [20, 50, 100, 200, 400, 800]
r_0 = [20]#[4, 10, 18, 25, 30, 40]
main(q_values, r_0, '3d_100_100_100','../../home/results/just_tests', 1, parallel=True, directed=False)
end = time.time()
print('zeit ', end-start)

KeyboardInterrupt: 

In [7]:
z = build_matrix('2d_100_100', np.array([100, 100, 1]), 4)
z.all_indices()
#z.one_int_index_tuples_and_adjacency()
#z.Laplacian_0()

(array([1]),)


TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Direct iteration is not supported for arrays with dimension > 1. Try using indexing instead.
[1] During: typing of intrinsic-call at /home/h3/s8583916/workspace/mthesis/matrix.py (101)

File "matrix.py", line 101:
    def fast_all_indices(D_0, N):
        <source elided>
                for k in range(N[2]):
                    for item in D_0:
                    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new


In [1]:
x=integer_inequality(np.array([100, 100, 1]))
x.all_numbers(49, d_given=[2,4,10,20,25,30,40])
x.save_to_json('2d_100_100')
#plt.show()

NameError: name 'integer_inequality' is not defined

In [4]:
import os

In [9]:
os.path.isdir('../../home')

True

In [15]:
%matplotlib qt
plt.imshow(z.L_rnd.toarray(), vmin=-1, vmax=1)

In [4]:
lam=np.zeros(10)
for i in range(10):
    z.random_rewiring(1)
    lam[i]=z.second_largest_eigenvalue(8, 1.2)/20
print(np.mean(lam))

-0.491432258197694


In [3]:
lam = np.zeros(100)
for i in range(100):
    z.random_rewiring(1)
    lam[i] = z.second_largest_eigenvalue()
print(np.mean(lam)/10)

1.2323772778806172


In [16]:
z.random_rewiring(1)
print(z.L_rnd.toarray())

[[-23.   0.   0. ...   0.   0.   0.]
 [  0. -21.   0. ...   0.   0.   1.]
 [  0.   0. -26. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ... -30.   0.   0.]
 [  0.   0.   0. ...   0. -19.   0.]
 [  0.   1.   0. ...   0.   0. -16.]]


In [3]:
z.random_rewiring(1)
print(z.second_largest_eigenvalue(8, 1.2)/20)

-0.49881384944856794


In [7]:
q_values = [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]
k_values = [20, 50, 100, 200, 400, 800]
dictq = {str(q):[] for q in q_values}
dictionary = {str(k):dictq for k in k_values}

In [6]:
dictionary[str(20)][str(1e-5)].append(1)

In [7]:
print(dictionary)

{'20': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '50': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '100': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '200': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '400': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '800': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}}


In [4]:
import networkx as nx

ModuleNotFoundError: No module named 'networkx'

In [6]:
np.random.binomial(200, 1)

200

In [12]:
from scipy.sparse import csr_matrix, triu, tril, find
A = csr_matrix([[1, 2, 0, 0, 3], [4, 5, 0, 6, 7], [0, 0, 8, 9, 0],[1,1,1,5,4],[0,0,0,3,4]],dtype='int32')

In [11]:
print(tril(A,k=4-5).toarray())

[[0 0 0 0 0]
 [4 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 0 0]
 [0 0 0 3 0]]


In [10]:
print(A.getrow(2).toarray())

[[0 0 8 9 0]]


In [18]:
print(find(triu(A,k=1)))

(array([0, 1, 2, 0, 1, 3], dtype=int32), array([1, 3, 3, 4, 4, 4], dtype=int32), array([2, 6, 9, 3, 7, 4], dtype=int32))


In [17]:
A_new =A
A_new+=A_new
print(A.toarray(), A_new.toarray())

[[1 2 0 0 3]
 [4 5 0 6 7]
 [0 0 8 9 0]
 [1 1 1 5 4]
 [0 0 0 3 4]] [[ 2  4  0  0  6]
 [ 8 10  0 12 14]
 [ 0  0 16 18  0]
 [ 2  2  2 10  8]
 [ 0  0  0  6  8]]


In [39]:
x = np.array([1,1,1,2,2,3,1,3,4,7,8])

In [40]:
np.bincount(x)

array([0, 4, 2, 2, 1, 0, 0, 1, 1], dtype=int64)

In [43]:
y = find(csc(x))
print(y)

NameError: name 'csc' is not defined

In [7]:
print(type(np.append([1,2,3],[2,2,3])))

<class 'numpy.ndarray'>


In [20]:
N = 1000
for k in [20, 50, 100]:
    print(k,N,2*np.sqrt(1/k -1/N)-1)

20 1000 -0.5572811275764269
50 1000 -0.7243190249581956
100 1000 -0.8102633403898972
