In [1]:
from matrix import build_matrix
from matrix import integer_inequality
import numpy as np
from scipy.sparse import coo_matrix
#from matplotlib import pyplot as plt
import scipy.sparse
from scipy.sparse.linalg import eigsh
from scipy.sparse.linalg import eigs
from Reproduce import main
import time

In [3]:
import numpy as np
import sys
print(sys.executable)

/software/generic/JupyterHub/test/bin/python


In [ ]:
start = time.time()
exponent = np.arange(16)
q_values = 10 ** (-exponent / 3)
q_values=[1]#[0.01, 0.1]
k_values = [800]#[20, 50, 100, 200, 400, 800]
main(q_values, k_values, '../../home/results/reproduce_1000_directed_with_averaging', 10, parallel=True, directed=True)
end = time.time()
print('zeit ', end-start)

[[-400, 0, 0], [-399, 0, 0], [-398, 0, 0], [-397, 0, 0], [-396, 0, 0], [-395, 0, 0], [-394, 0, 0], [-393, 0, 0], [-392, 0, 0], [-391, 0, 0], [-390, 0, 0], [-389, 0, 0], [-388, 0, 0], [-387, 0, 0], [-386, 0, 0], [-385, 0, 0], [-384, 0, 0], [-383, 0, 0], [-382, 0, 0], [-381, 0, 0], [-380, 0, 0], [-379, 0, 0], [-378, 0, 0], [-377, 0, 0], [-376, 0, 0], [-375, 0, 0], [-374, 0, 0], [-373, 0, 0], [-372, 0, 0], [-371, 0, 0], [-370, 0, 0], [-369, 0, 0], [-368, 0, 0], [-367, 0, 0], [-366, 0, 0], [-365, 0, 0], [-364, 0, 0], [-363, 0, 0], [-362, 0, 0], [-361, 0, 0], [-360, 0, 0], [-359, 0, 0], [-358, 0, 0], [-357, 0, 0], [-356, 0, 0], [-355, 0, 0], [-354, 0, 0], [-353, 0, 0], [-352, 0, 0], [-351, 0, 0], [-350, 0, 0], [-349, 0, 0], [-348, 0, 0], [-347, 0, 0], [-346, 0, 0], [-345, 0, 0], [-344, 0, 0], [-343, 0, 0], [-342, 0, 0], [-341, 0, 0], [-340, 0, 0], [-339, 0, 0], [-338, 0, 0], [-337, 0, 0], [-336, 0, 0], [-335, 0, 0], [-334, 0, 0], [-333, 0, 0], [-332, 0, 0], [-331, 0, 0], [-330, 0, 0], [-329

In [2]:
z = build_matrix('1d_ring_1000', np.array([1000, 1, 1]), 10)
z.all_indices()
z.one_int_index_tuples_and_adjacency()
z.Laplacian_0()

[[-10, 0, 0], [-9, 0, 0], [-8, 0, 0], [-7, 0, 0], [-6, 0, 0], [-5, 0, 0], [-4, 0, 0], [-3, 0, 0], [-2, 0, 0], [-1, 0, 0], [1, 0, 0], [2, 0, 0], [3, 0, 0], [4, 0, 0], [5, 0, 0], [6, 0, 0], [7, 0, 0], [8, 0, 0], [9, 0, 0], [10, 0, 0]]
edges 20000


In [3]:
743/60

12.383333333333333

In [4]:
import os

In [9]:
os.path.isdir('../../home')

True

In [15]:
%matplotlib qt
plt.imshow(z.L_rnd.toarray(), vmin=-1, vmax=1)

In [4]:
lam=np.zeros(10)
for i in range(10):
    z.random_rewiring(1)
    lam[i]=z.second_largest_eigenvalue(8, 1.2)/20
print(np.mean(lam))

-0.491432258197694


In [3]:
lam = np.zeros(100)
for i in range(100):
    z.random_rewiring(1)
    lam[i] = z.second_largest_eigenvalue()
print(np.mean(lam)/10)

1.2323772778806172


In [16]:
z.random_rewiring(1)
print(z.L_rnd.toarray())

[[-23.   0.   0. ...   0.   0.   0.]
 [  0. -21.   0. ...   0.   0.   1.]
 [  0.   0. -26. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ... -30.   0.   0.]
 [  0.   0.   0. ...   0. -19.   0.]
 [  0.   1.   0. ...   0.   0. -16.]]


In [3]:
z.random_rewiring(1)
print(z.second_largest_eigenvalue(8, 1.2)/20)

-0.49881384944856794


In [7]:
q_values = [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]
k_values = [20, 50, 100, 200, 400, 800]
dictq = {str(q):[] for q in q_values}
dictionary = {str(k):dictq for k in k_values}

In [6]:
dictionary[str(20)][str(1e-5)].append(1)

In [7]:
print(dictionary)

{'20': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '50': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '100': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '200': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '400': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}, '800': {'1e-05': [1], '0.0001': [], '0.001': [], '0.01': [], '0.1': []}}


In [4]:
import networkx as nx

ModuleNotFoundError: No module named 'networkx'

In [6]:
np.random.binomial(200, 1)

200

In [12]:
from scipy.sparse import csr_matrix, triu, tril, find
A = csr_matrix([[1, 2, 0, 0, 3], [4, 5, 0, 6, 7], [0, 0, 8, 9, 0],[1,1,1,5,4],[0,0,0,3,4]],dtype='int32')

In [11]:
print(tril(A,k=4-5).toarray())

[[0 0 0 0 0]
 [4 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 0 0]
 [0 0 0 3 0]]


In [10]:
print(A.getrow(2).toarray())

[[0 0 8 9 0]]


In [18]:
print(find(triu(A,k=1)))

(array([0, 1, 2, 0, 1, 3], dtype=int32), array([1, 3, 3, 4, 4, 4], dtype=int32), array([2, 6, 9, 3, 7, 4], dtype=int32))


In [17]:
A_new =A
A_new+=A_new
print(A.toarray(), A_new.toarray())

[[1 2 0 0 3]
 [4 5 0 6 7]
 [0 0 8 9 0]
 [1 1 1 5 4]
 [0 0 0 3 4]] [[ 2  4  0  0  6]
 [ 8 10  0 12 14]
 [ 0  0 16 18  0]
 [ 2  2  2 10  8]
 [ 0  0  0  6  8]]


In [39]:
x = np.array([1,1,1,2,2,3,1,3,4,7,8])

In [40]:
np.bincount(x)

array([0, 4, 2, 2, 1, 0, 0, 1, 1], dtype=int64)

In [43]:
y = find(csc(x))
print(y)

NameError: name 'csc' is not defined

In [7]:
print(type(np.append([1,2,3],[2,2,3])))

<class 'numpy.ndarray'>


In [20]:
N = 1000
for k in [20, 50, 100]:
    print(k,N,2*np.sqrt(1/k -1/N)-1)

20 1000 -0.5572811275764269
50 1000 -0.7243190249581956
100 1000 -0.8102633403898972
